version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  metis:
    image: lblod/frontend-data.lblod.info:0.2.2
    links:
      - identifier:backend
    environment:
      EMBER_BASE_URL: "http://data.lblod.info/"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  identifier:
    image: semtech/mu-identifier:1.8.0
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0-beta.1
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend:
    image: lblod/frontend-centrale-vindplaats
    volumes:
      - ./config/frontend:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  uri-info:
    image: redpencil/mu-uri-info-service:0.1.0
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  download-url:
    image: lblod/download-url-service
    links:
      - database:database
    volumes:
      - ./data/files:/share
    environment:
      CACHING_MAX_RETRIES: 300
      CACHING_CRON_PATTERN: '0 */15 * * * *'
      MAX_PENDING_TIME_IN_SECONDS: 7200
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  harvesting-initiation:
    image: lblod/harvesting-initiation-service:0.1.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  harvest-collector:
    image: lblod/harvest-collector-service:0.0.3
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  harvesting-import:
    image: lblod/harvesting-import-service:latest
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
