version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  resource-labels:
    image: lblod/resource-label-service:0.3.1
    restart: always
    environment:
      DEFAULT_LANGUAGE: 'nil'
    links:
      - virtuoso:database
    labels:
      - "logging=true"
  identifier:
    image: semtech/mu-identifier:1.9.0
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}, {\"variables\":[],\"name\":\"clean\"}]"
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.1
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend:
    image: lblod/frontend-centrale-vindplaats:0.2.0.fastboot
    environment:
      EMBER_METIS_BASE_URL: "http://data.lblod.info/"
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.19.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    networks:
      default:
      app-centrale-vindplaats:
        aliases:
            - virtuoso
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
networks:
  app-centrale-vindplaats:
    external: true
