version: '3.7'

services:
  resource-labels:
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  frontend:
    restart: "no"
  frontend-harvesting-self-service:
    restart: "no"
  migrations:
    restart: "no"
  database:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  uri-info:
    restart: "no"
  deltanotifier:
    restart: "no"
  file:
    restart: "no"
  harvesting-download-url:
    environment:
      CACHING_MAX_RETRIES: 5
    restart: "no"
  harvest-collector:
    restart: "no"
  harvesting-import:
    restart: "no"
  harvesting-sameas:
    restart: "no"
  job-controller-service:
    restart: "no"
