version: '3.7'

services:
  resource-labels:
    restart: "no"
  uri-info:
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "8080:80"
  dispatcher:
    restart: "no"
  frontend:
    restart: "no"
  migrations:
    restart: "no"
  database:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  deltanotifier:
    restart: "no"
