version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  resource-labels:
    image: lblod/resource-label-service:0.3.1
    restart: always
    environment:
      DEFAULT_LANGUAGE: 'nil'
    links:
      - virtuoso:database
    labels:
      - "logging=true"
  identifier:
    image: semtech/mu-identifier:1.9.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}, {\"variables\":[],\"name\":\"clean\"}]"
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: cecemel/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      LOG_OUTGOING_SPARQL_QUERY_ROUNDTRIP: "true"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.19.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini # Note: on production override this setting
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  login:
    image: aatauil/mu-node-authentication-service:0.0.2
    environment:
      NODE_ENV: "development"
      ACCOUNTS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    volumes:
      - /media/achraf/Main/projects/mu-semtech/mu-node-authentication-service/:/app/
    links:
      - virtuoso:db
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: cecemel/delta-notifier:0.2.0-beta.2
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging