version: '3.7'

services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  frontend:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  uri-info:
    restart: "no"
  harvesting-import:
    restart: "no"
  job-controller-service:
    restart: "no"
